### ISSUE TITLE
On app resume on android htc one

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#119]
@rdougan On app resume, it crashed with following error:

java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
	at org.apache.cordova.contacts.ContactAccessorSdk5.search(ContactAccessorSdk5.java:186)
	at org.apache.cordova.contacts.ContactManager$1.run(ContactManager.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by rdougan** [comment]
This appears to be a java error with the android contacts plugin. can you try removing the contacts plugin and fetch it directly from the git repo?

    cordova plugin remove cordova-plugin-contacts
    cordova plugin add https://github.com/apache/cordova-plugin-contacts.git

**Comment by shikarkhane** [comment]
this fixed the issue. thank u
